# GitHub Actions Vue Demo
name: Vue App Build and Deploy # åç§°
on:
  push:
    branches:
      - master # master åˆ†æ”¯å‘ç”Ÿpushäº‹ä»¶æ—¶è§¦å‘
jobs:
  build-and-deploy: # ä»»åŠ¡
    runs-on: ubuntu-latest # è¿è¡Œç¯å¢ƒ
    steps: # è¿è¡Œæ­¥éª¤
      - name: Checkout
        uses: actions/checkout@master # è·å–æºç 

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # - name: Install and Build
      #   run: |
      #     npm install
      #     npm build:prod

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b5_34048785
          # ftp password
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /htdocs/admin/
